### PR TITLE
[Pods] Update Hyperdrive to 0.3.0

### PR DESCRIPTION
**Pull request by kylef**
This also updates the CocoaPods version, and thus results in project settings changes.

### CODE REVIEW

**Comment by kylef** [comment]
CircleCI is broken (also, OS X is now separately paid).

**Comment by kylef** [comment]
I've updated the PR to switch to Travis CI since it's more reliable than CircleCI and used in Hyperdrive for same reason.

**Comment by w-vi** [comment]
Looks good but travis needs a bit of tweaking :/

**Comment by kylef** [comment]
Got this passing, should be good to merge now @w-vi.

**Pull request merged**
